#!/bin/bash
clear
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa executar como root\033[0m"
rm $HOME/Plus* > /dev/null 2>&1; exit 0
}
barra="\033[0;34m═════════════════════════════════════════════════\033[0m"
_lnk=$(echo 't1:e#n.5s0ul&p4hs$s.0729t9p$&8i&&9r7827c032:3s'| sed -e 's/[^a-z.]//ig'| rev)
_Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig')
_1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')

cd $HOME
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mWAIT \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mWAIT \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}

function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev)
chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
  echo -e "\n\033[1;31mLIST INVÁLIDA!\033[0m"
  rm -rf $HOME/Plus* > /dev/null 2>&1
  sleep 2
  clear; exit 1
}
}

function verif_db () {
[[ -f "$HOME/usuarios.db" ]] && {
    echo -e "\033[0;34m═════════════════════════════════════════════════\033[0m"
    echo -e "\033[1;31mATTENTION! \033[0m"
    echo -e "\033[1;33mA user database \033[1;32m(usuarios.db) \033[1;33mwas" 
    echo -e "FOUND!, You want to keep it to preserve its limits"
    echo -e "of simultaneous user connections ? or do you want"
    echo -e "create a new Database ?\033[0m"
    echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mKeep Current Database\033[0m"
    echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCreate a new database \033[0m"
    echo -e "\033[0;34m═════════════════════════════════════════════════\033[0m"
    #tput setaf 2 ; tput bold ; read -p "Opción ?: " -e -i 1 optiondb ; tput sgr0
    read -p "$(echo -e "\033[1;32mOption ? \033[1;33m[1-2]:\033[1;37m ")" -e -i 1 optiondb
} || {
	awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
}
[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
}

fun_attlist () {
    apt-get update -y
	[[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
	echo "crz: $(date)" > /usr/share/.plus/.plus
}

inst_pct () {
_pacotes=("gawk" "mlocate" "bc" "screen" "nano" "zip" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "ufw" "python" "python3" "python-pip")
for _prog in ${_pacotes[@]}; do
    apt install $_prog -y
done
pip install speedtest-cli
apt-get install python-pip build-essential python-dev -y
apt install glances -y
pip install Glances
pip install PySensors
}

color_prompt () {
cp /etc/skel/.bashrc ~/.bashrc
sed -i "s/#force_color_prompt=yes/force_color_prompt=yes/g" /root/.bashrc
source ~/.bashrc
}

echo -e "$barra"
echo -e "\E[44;1;37m         WELCOME TO ADMPLUS MANAGER PRO          \E[0m"
echo -e "$barra"
echo -e "\033[1;31m¡ATTENTION! \033[1;33mTHIS SCRIPT WILL GO TO !\033[0m"
echo ""
echo -e " \033[1;31m• \033[1;33mINSTALL A SET OF SCRIPTS AS TOOLS\033[0m" 
echo -e " \033[1;33m  FOR MANAGEMENT OF NETWORKS, SYSTEMS AND USERS\033[0m"
echo ""
echo -e " \033[1;32m• \033[1;32mTIP! \033[1;33mUSE THE DARK THEME IN YOUR TERMINAL\033[0m"
echo -e " \033[1;33m  TO A BETTER EXPERIENCE AND VISUALIZATION\033[0m"
echo -e " \033[1;33m  OF THE SAME!\033[0m"
echo -e "$barra"
read -p "$(echo -e "\033[1;36mDO YOU WANT TO CONTINUE \033[1;33m[Y/n]:\033[1;37m ")" -e -i y resp
[[ $resp = @(n|N) ]] && rm $HOME/Plus* && exit 0
_lnk2=$(echo "$key"|awk -F : '{print $2}')
_lnk1=$(echo "$key"|awk -F : '{print $1}')
rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/ADMPLUS-MANAGER-PRO/main/Install/list > /dev/null 2>&1; verif_key
sleep 1s
verif_db
echo -e "$barra"
echo -e "\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mUPDATING SYSTEM \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
fun_bar 'fun_attlist'
echo -e "$barra"
echo -e "\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mPACKAGE INSTALLATION \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
fun_bar 'inst_pct'
echo -e "$barra"
[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
echo -e "$barra"
echo -e "\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mENDING \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
cd $HOME
color_prompt
echo -e "$barra"
echo -e "\033[1;32mINSTALACIÓN COMPLETA \033[0m"
echo -e "\033[1;31m\033[1;33mINSTALLATION COMPLETE: \033[1;32mmenu / adm\033[0m"
echo -e "\033[1;33mINFORMATION \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@AAAAAEXQOSyIpN2JZ0ehUQ\033[0m"
echo -e "$barra"
rm $HOME/Plus* && cat /dev/null > ~/.bash_history && history -c
