#!/bin/bash
# MENU APACHE V3.5 
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
[[ ! -e /usr/lib/sshplus ]] && rm -rf /bin/menu > /dev/null 2>&1
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "\033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "\033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
IP=$(cat /etc/IP)
x="ok"
gestorapache2 ()
{
port () {
local portas
local portas_var=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN")
i=0
while read port; do
var1=$(echo $port | awk '{print $1}') && var2=$(echo $port | awk '{print $9}' | awk -F ":" '{print $2}')
[[ "$(echo -e ${portas}|grep -w "$var1 $var2")" ]] || {
    portas+="$var1 $var2 $portas"
    echo "$var1 $var2"
    let i++
    }
done <<< "$portas_var"
}

verify_port () {
local SERVICE="$1"
local PORTENTRY="$2"
[[ ! $(echo -e $(port|grep -v ${SERVICE})|grep -w "$PORTENTRY") ]] && return 0 || return 1
}

apache2_install () {
clear
echo -e "\033[01;32mINSTALANDO APACHE2... "
echo ""
echo -e "\033[1;32mADICIONANDO PUERTA 81 !"
echo ""
fun_bar "apt-get install apache2 -y"
sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf
echo ""
echo -e "\033[1;32mREINICIANDO APACHE2!"
echo ""
fun_bar 'service apache2 start' 'service apache2 restart'
echo ""
echo -e "\033[01;32m APACHE CONFIGURADO CON ÉXITO"
echo ""
sleep 2s
conexao
exit
}

remover_apache2 () {
clear
echo -e "\033[01;32mDESINTALANDO APACHE2... "
echo ""
purge_apache () {
/etc/init.d/apache2 stop
service apache2 stop
apt-get purge apache2 -y
}
fun_bar "purge_apache"
echo ""
echo -e "\033[01;32m APACHE2 DESINLADO CON ÉXITO"
[[ -d /etc/apache2 ]] && rm -rf /etc/apache2
echo ""
sleep 2s
conexao
exit
}

edit_apache () {
clear
echo -e "\033[01;32mREDEFINIR PUERTA APACHE2 "
echo ""
local CONF="/etc/apache2/ports.conf"
local NEWCONF="$(cat ${CONF})"
echo -ne "\033[01;37mNueva Puerta: "
read -p "" newports
for PTS in `echo ${newports}`; do
verify_port apache "${PTS}" && echo -e "\033[1;33mPort $PTS \033[1;32mOK" || {
echo -e "\033[1;33mPort $PTS \033[1;31mFAIL"
service apache2 restart &>/dev/null
echo ""
sleep 2s
gestorapache2
exit
}
done
rm ${CONF}
while read varline; do
if [[ $(echo ${varline}|grep -w "Listen") ]]; then
 if [[ -z ${END} ]]; then
 echo -e "Listen ${newports}" >> ${CONF}
 END="True"
 else
 echo -e "${varline}" >> ${CONF}
 fi
else
echo -e "${varline}" >> ${CONF}
fi
done <<< "${NEWCONF}"
echo -e "\033[01;36mAGUARDE"
service apache2 restart &>/dev/null
sleep 1s
echo ""
echo -e "\033[1;32m PUERTA REDEFINIDA"
echo ""
sleep 2s
gestorapache2
exit
}

fun_iniciastop () {
if [[ ! -e /etc/apache2/apache_stop ]]; then
echo -e "\033[1;32mPARANDO APACHE2..."
echo ""
/etc/init.d/apache2 stop > /dev/null 2>&1
fun_bar "service apache2 stop"
echo "#STOP" > /etc/apache2/apache_stop
echo ""
echo -e "\033[1;32m APACHE2 PARADO CON ÉXITO"
echo ""
sleep 2s
gestorapache2
exit
fi
echo -e "\033[1;32mINICIANDO APACHE2..."
echo ""
service apache2 start > /dev/null 2>&1
fun_bar "service apache2 restart"
rm -rf /etc/apache2/apache_stop
echo ""
echo -e "\033[1;32m APACHE ACTIVADO CON ÉXITO"
echo ""
sleep 2s
gestorapache2
exit
}

mine_port () {
local portasVAR=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN")
local NOREPEAT
local reQ
local Port
while read port; do
reQ=$(echo ${port}|awk '{print $1}')
Port=$(echo {$port} | awk '{print $9}' | awk -F ":" '{print $2}')
[[ $(echo -e $NOREPEAT|grep -w "$Port") ]] && continue
NOREPEAT+="$Port\n"
case ${reQ} in
apache|apache2)
[[ -z $APC ]] && echo "" && local APC="\033[1;33mPUERTA\033[1;37m: \033[1;32m"
APC+="$Port ";;
esac
done <<< "${portasVAR}"
[[ ! -z $APC ]] && echo -e $APC
}

while true $x != "ok"
do
if [[ ! -e /etc/apache2/ports.conf ]]; then
apache2_install
exit 1
fi
clear
unset OPENBAR
[[ $(port|grep -w "apache2") ]] && OPENBAR="\033[1;32m...[\033[1;32m♦\033[1;32m] " || OPENBAR="\033[1;31m...[\033[1;31m○\033[1;31m] "
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[44;1;37m              GESTIONAR  APACHE2                  \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
mine_port
echo ""
echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;33mDESINTALAR APACHE2 \033[1;31m   
[\033[1;36m02\033[1;31m] \033[1;37m• \033[1;33mREDEFINIR PORTA \033[1;31m
[\033[1;36m03\033[1;31m] \033[1;37m• \033[1;33mEDITAR CLIENTE \033[1;31m(comand nano)\033[1;31m                  
[\033[1;36m04\033[1;31m] \033[1;37m• \033[1;33mINICIAR OU PARAR $OPENBAR \033[1;31m
[\033[1;36m00\033[1;31m] \033[1;37m• \033[1;33mVOLVER AL MENU \033[1;32m<\033[1;33m<\033[1;31m< \033[1;31m"
echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo ""
echo -ne "\033[1;32mOPCION \033[1;33m?\033[1;31m?\033[1;37m : "; read x

case "$x" in 
   1 | 01)
   clear
   remover_apache2
   ;;
   2 | 02)
   clear
   edit_apache
   ;;
   3 | 03)
   clear
   nano /etc/apache2/ports.conf
   service apache2 restart > /dev/null 2>&1
   ;;
   4 | 04)
   clear
   fun_iniciastop
   ;;
   5 | 05)
   clear
   senharoot
   sleep 3
   ;;
   0 | 00)
   conexao
   exit;
   ;;
   *)
   echo -e "\n\033[1;31mOpción inválida !\033[0m"
   sleep 1
esac
done
}
gestorapache2
#fim