#!/bin/bash

echo -e "\033[1;31mATENCIÓN!!\033[0m"
echo " "
echo -e "\033[1;33mEsta contraseña se utilizará para iniciar sesión en su servidor \033[0m"
echo " "
echo -ne "\033[1;32mINGRESE UNA NUEVA CONTRASEÑA\033[1;37m: "; read senha
[[ -z "$senha" ]] && {
echo -e "\n\033[1;31mCONTRASEÑA INVALIDA !\033[0m"
exit 0
}
echo "root:$senha" | chpasswd
sleep 1s
echo -e "\n\033[1;32mCONTRASEÑA CAMBIADA CON ÉXITO!\033[0m"
sleep 3s
cd
clear

