#!/bin/bash

echo -e "\033[1;31mATENCAO!!\033[0m"
echo " "
echo -e "\033[1;33mEssa senha sera usada para entrar no seu servidor \033[0m"
echo " "
echo -ne "\033[1;32mDIGITE A NOVA SENHA\033[1;37m: "; read senha
[[ -z "$senha" ]] && {
echo -e "\n\033[1;31mSENHA INVALIDA !\033[0m"
exit 0
}
echo "root:$senha" | chpasswd
sleep 1s
echo -e "\n\033[1;32mSENHA ALTERADA COM SUCESSO!\033[0m"
sleep 3s
cd
clear

