#!/bin/bash
mportas () {
unset portas
portas_var=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN")
while read port; do
var1=$(echo $port | awk '{print $1}') && var2=$(echo $port | awk '{print $9}' | awk -F ":" '{print $2}')
[[ "$(echo -e $portas|grep "$var1 $var2")" ]] || portas+="$var1 $var2\n"
done <<< "$portas_var"
i=1
echo -e "$portas"
}
fun_shadowsocks () {
[[ -e /etc/shadowsocks.json ]] && {
[[ $(ps x|grep ssserver|grep -v grep|awk '{print $1}') != "" ]] && kill -9 $(ps x|grep ssserver|grep -v grep|awk '{print $1}') > /dev/null 2>&1 && ssserver -c /etc/shadowsocks.json -d stop > /dev/null 2>&1
echo -e "\033[0;31mSHADOWSOCKS PARADO"
echo ""
rm /etc/shadowsocks.json
return 0
}
       echo -e "\033[1;32mINSTALADOR SHADOWSOCKS"
       echo ""
       while true; do
       echo -e "\033[0;32mSelecione ua Criptografia"
       echo ""
       encript=(aes-256-gcm aes-192-gcm aes-128-gcm aes-256-ctr aes-192-ctr aes-128-ctr aes-256-cfb aes-192-cfb aes-128-cfb camellia-128-cfb camellia-192-cfb camellia-256-cfb chacha20-ietf-poly1305 chacha20-ietf chacha20 rc4-md5)
       for((s=0; s<${#encript[@]}; s++)); do
       echo -e " [${s}] - ${encript[${s}]}"
       done
       echo ""
       while true; do
       unset cript
       echo -ne " Qual Criptografia? Escolha uma Opcao: "; read -e -i 0 cript
       [[ ${encript[$cript]} ]] && break
       echo -e "\033[0;31mOpcao Invalida"
       done
       encriptacao="${encript[$cript]}"
       [[ ${encriptacao} != "" ]] && break
       eecho -e "\033[0;31mOpcao Invalida"
      done
#ESCOLHENDO LISTEN
      echo ""
      echo -e "\033[0;32mSelecione Uma Porta Para o Shadowsocks Escutar"
      echo ""
      while true; do
      unset Lport
      read -p " Listen Port: " Lport
      [[ $(mportas|grep "$Lport") = "" ]] && break
      echo -e " ${Lport}: Porta Invalida"      
      done
#INICIANDO
echo ""
echo -e "\033[0;32mDigite a Senha Shadowsocks"
read -p" Pass: " Pass
echo ""
echo -e "\033[0;32mInstalando"
echo ""
fun_bar 'apt-get install python-pip python-m2crypto -y'
fun_bar 'pip install shadowsocks'
echo -ne '{\n"server":"' > /etc/shadowsocks.json
echo -ne "0.0.0.0" >> /etc/shadowsocks.json
echo -ne '",\n"server_port":' >> /etc/shadowsocks.json
echo -ne "${Lport},\n" >> /etc/shadowsocks.json
echo -ne '"local_port":1080,\n"password":"' >> /etc/shadowsocks.json
echo -ne "${Pass}" >> /etc/shadowsocks.json
echo -ne '",\n"timeout":600,\n"method":"aes-256-cfb"\n}' >> /etc/shadowsocks.json
echo ""
echo -e "\033[0;33m STARTING\033[0m"
ssserver -c /etc/shadowsocks.json -d start > /dev/null 2>&1
value=$(ps x |grep ssserver|grep -v grep)
[[ $value != "" ]] && value="\033[1;32mSTARTED" || value="\033[1;31mERROR"
echo ""
echo -e "\033[0;32m ${value} "
echo ""
return 0
}
fun_shadowsocks