#!/bin/bash
#-----TheMentalistSay------
fun_swap() {
    clear
		echo -e "\E[44;1;37m            GESTIONAR MEMORIA VIRTUAL             \E[0m"
        echo ""
        echo -e "\033[1;31mSwap es un área de intercambio utilizada para aumentar la cantidad de \033[0m"
        echo -e "\033[1;31mmemoria RAM (RECOMENDADO PARA MÁQUINAS CON POCA RAM). \033[0m"
        echo -e "\033[1;31mAntes de activar, conozca la cantidad de almacenamiento que tiene su máquina, \033[0m"
        echo -e "\033[1;31msiempre deje mucho espacio de almacenamiento para evitar choques. \033[0m"
        echo ""
		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mACTIVAR O CAMBIAR VALOR SWAP \033[0m"
		echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mDESACTIVAR SWAP\033[0m"
		echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLVER AL MENU\033[0m"
		echo ""
		echo -ne "\033[1;32mOPCION \033[1;33m?\033[1;37m "
		read resposta
		if [[ "$resposta" = '1' ]]; then
            clear
			echo -e "\E[44;1;37m            MEMORIA VIRTUAL              \E[0m"
			echo ""
			echo -ne "\033[1;32mCUANTOS GIGAS QUIERES UTILIZAR \033[1;33m?\033[1;37m: "
			read gigas
            [[ -z "$gigas" ]] && {
					echo ""
					echo -e "\033[1;31mGigas no válido!"
					sleep 2
					clear
					ferramentascodes
				}
            echo ""
			echo -e "\033[1;32mINICIANDO MEMORIA VIRTUAL \033[1;31m$gigas GB\033[1;33m"
			echo ""
            swapoff -a
            rm -rf /bin/ram.img > /dev/null 2>&1
            fallocate -l ${gigas}G /bin/ram.img > /dev/null 2>&1
            chmod 600 /bin/ram.img > /dev/null 2>&1
            mkswap /bin/ram.img > /dev/null 2>&1
            swapon /bin/ram.img > /dev/null 2>&1
            echo 50  > /proc/sys/vm/swappiness
            echo '/bin/ram.img none swap sw 0 0' | sudo tee -a /etc/fstab > /dev/null 2>&1
            echo ""
			echo -e "\033[1;32m MEMORIA VIRTUAL ACTIVADA CON ÉXITO ! \033[1;33m"
            sleep 2
			fun_swap
        elif [[ "$resposta" = '2' ]]; then
            clear
			echo -e "\E[44;1;37m           DESACTIVANDO MEMORIA VIRTUAL              \E[0m"
            swapoff -a
            rm -rf /bin/ram.img > /dev/null 2>&1
            echo ""
			echo -e "\033[1;32m MEMORIA VIRTUAL DESACTIVADA CON ÉXITO ! \033[1;33m"
			sleep 2
			fun_swap
        elif [[ "$resposta" = '0' ]]; then
			echo ""
			echo -e "\033[1;31mRetornando...\033[0m"
			sleep 1
			ferramentascodes
		else
			echo ""
			echo -e "\033[1;31mOpción inválida !\033[0m"
			sleep 1
			fun_swap
		fi 
}
fun_swap