#!/bin/bash
clear

TCPspeed () {
if [[ `grep -c "^#ADM" /etc/sysctl.conf` -eq 0 ]]; then
#INSTALA
echo -e "\033[1;32mTCP SPEED NAO HABILITADO, VOCE GOSTARIA DE HABILITAR AGORA ? \033[0m"
echo ""
read -p "$(echo -ne "\033[1;32mO QUE VOCE QUER FAZER \033[1;31m? \033[1;33m[s/n]:\033[1;37m ") " -e -i s resposta
[[ "$resposta" = @(s|S|y|Y) ]] && {
echo "#ADM" >> /etc/sysctl.conf
echo "net.ipv4.tcp_window_scaling = 1
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 16384 16777216
net.ipv4.tcp_low_latency = 1
net.ipv4.tcp_slow_start_after_idle = 0" >> /etc/sysctl.conf
sysctl -p /etc/sysctl.conf > /dev/null 2>&1
echo -e "\n\033[1;32m TCP ATIVADO ! \033[0m"
sleep 3
utilscodes
} || echo -e "\n\033[1;31m CANCELADO ! \033[0m"
 sleep 3
 utilscodes
 else
#REMOVE
echo -e "\033[1;32mA VELOCIDADE TCP JA ESTA HABILITADA, DESEJA DESATIVAR AGORA ? \033[0m"
echo ""
read -p "$(echo -ne "\033[1;32mO QUE VOCE QUER FAZER \033[1;31m? \033[1;33m[s/n]:\033[1;37m ") " -e -i n resposta
[[ "$resposta" = @(s|S|y|Y) ]] && {
grep -v "^#ADM
net.ipv4.tcp_window_scaling = 1
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 16384 16777216
net.ipv4.tcp_low_latency = 1
net.ipv4.tcp_slow_start_after_idle = 0" /etc/sysctl.conf > /tmp/syscl && mv -f /tmp/syscl /etc/sysctl.conf
sysctl -p /etc/sysctl.conf > /dev/null 2>&1
echo -e "\n\033[1;31m TCP PARADO ! \033[0m"
sleep 3
utilscodes
} || echo -e "\n\033[1;31m CANCELADO ! \033[0m"
sleep 3
utilscodes
fi
}
TCPspeed
