#!/bin/bash
clear
fun_prog ()
{
	comando[0]="$1" 
    ${comando[0]}  > /dev/null 2>&1 & 
	tput civis
	echo -ne "\033[1;32m.\033[1;33m.\033[1;31m. \033[1;32m"
    while [ -d /proc/$! ]
	do
		for i in / - \\ \|
		do
			sleep .1
			echo -ne "\e[1D$i"
		done
	done
	tput cnorm
	echo -e "\e[1DOK"
}
echo -ne "\033[1;33mAPLICANDO UPDATE"; fun_prog 'apt-get update -y'
apt-get update -y > /dev/null 2>&1
echo ""
sleep 1
echo -ne "\033[1;33mAPLICANDO UPGRADE"; fun_prog 'apt-get upgrade -y'
apt-get upgrade -y > /dev/null 2>&1
echo ""
sleep 1
# echo -ne "\033[1;33mAPLICANDO DIST-UPGRADE"; fun_prog 'apt-get dist-upgrade -y'
# apt-get update -y > /dev/null 2>&1
# echo ""
# sleep 1
# echo -ne "\033[1;33mAPLICANDO FULL-UPGRADE"; fun_prog 'apt-get full-upgrade -y'
# apt-get update -y > /dev/null 2>&1
# echo ""
# sleep 1
# echo -e "\033[1;32mACTUALIZACION EXITOSA DEL SISTEMA!\033[0m"
# sleep 1
